name: CI of mc_rtc_ros

on:
  push:
    paths-ignore:
      # Changes to those files don't mandate running CI
      - ".gitlab-ci.yml"
      - ".jrl-ci"
      - ".github/workflows/package.yml"
      - "debian/**"
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        ubuntu: |
          apt-mirrors:
            mc-rtc:
              cloudsmith: mc-rtc/head
          apt: libmc-rtc-dev libqwt-qt5-dev
        ros: |
          apt: mc-rtc-plugin
    - name: Build with colcon
      uses: jrl-umi3218/github-actions/build-colcon-project@master
    - name: Slack Notification
      if: failure()
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: '#ci'
        slack-text: >
          [mc_rtc_ros] Build *${{ matrix.os }}/${{ matrix.build-type }} (${{ matrix.compiler }})* failed on ${{ github.ref }}
